/**
 * PDF Generation using pdfkit
 */

import PDFDocument from 'pdfkit';

export interface GeneratePDFOptions {
  content: string;
  title: string;
  isWatermarked: boolean;
  metadata?: {
    author?: string;
    subject?: string;
    keywords?: string;
  };
}

export function generatePDF(options: GeneratePDFOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: options.title,
          Author: options.metadata?.author || 'DocMint',
          Subject: options.metadata?.subject || 'Legal Document',
          Keywords: options.metadata?.keywords || 'legal, contract, document',
          Creator: 'DocMint - AI-Powered Document Generation',
        },
      });

      const buffers: Buffer[] = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      // Professional Header with Logo Area
      doc
        .fontSize(24)
        .font('Helvetica-Bold')
        .fillColor('#1e40af')
        .text('DocMint', 50, 50, {
          align: 'left',
        })
        .fontSize(10)
        .fillColor('#6b7280')
        .text('AI-Powered Document Platform', 50, 75);

      // Title
      doc
        .fontSize(20)
        .font('Helvetica-Bold')
        .fillColor('#000000')
        .text(options.title, {
          align: 'center',
          y: 100,
        });

      doc.moveDown(2);

      // Enhanced Watermark for free users
      if (options.isWatermarked) {
        doc
          .fontSize(50)
          .fillColor('#e5e7eb')
          .opacity(0.3)
          .text('DRAFT - NOT REVIEWED', {
            align: 'center',
            x: doc.page.width / 2,
            y: doc.page.height / 2,
            width: 500,
            angle: 45,
          })
          .opacity(1);
      }

      // Reset color and position
      doc.fillColor('#000000');

      // Content
      const lines = options.content.split('\n');
      doc.fontSize(11).font('Helvetica');

      lines.forEach((line) => {
        if (line.trim().startsWith('##')) {
          // Section headers
          doc.moveDown(0.5).fontSize(14).font('Helvetica-Bold').text(line.replace(/^#+\s*/, ''));
          doc.fontSize(11).font('Helvetica');
        } else if (line.trim()) {
          doc.text(line, { align: 'left', continued: false });
        } else {
          doc.moveDown(0.5);
        }
      });

      // Footer
      const pageCount = doc.bufferedPageRange().count;
      for (let i = 0; i < pageCount; i++) {
        doc.switchToPage(i);

        // Footer text
        doc
          .fontSize(8)
          .fillColor('#666666')
          .text(
            `Generated by DocMint - AI-Powered Document Platform | NOT legal advice`,
            50,
            doc.page.height - 40,
            {
              align: 'center',
              width: doc.page.width - 100,
            }
          );

        // Page number
        doc.text(`Page ${i + 1} of ${pageCount}`, 50, doc.page.height - 30, {
          align: 'center',
          width: doc.page.width - 100,
        });
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
