import { IComplianceChecklist } from '@/types/document';

/**
 * Seed data for compliance checklists
 * These are informational only - NOT legal advice
 */

export const SEED_CHECKLISTS: Partial<IComplianceChecklist>[] = [
  // US - Tech Freelancer Compliance
  {
    country: 'US',
    industry: 'tech',
    name: 'US Tech Freelancer Compliance Checklist',
    description: 'Basic tax and compliance checklist for US-based technology freelancers',
    version: 1,
    isActive: true,
    items: [
      {
        id: 'us-tech-1',
        title: 'Register Business Entity',
        description: 'Decide on business structure (Sole Proprietor, LLC, S-Corp). Most freelancers start as Sole Proprietors.',
        category: 'registration',
        priority: 'high',
        isRequired: true,
      },
      {
        id: 'us-tech-2',
        title: 'Obtain EIN (Employer Identification Number)',
        description: 'Get an EIN from the IRS (free) if you form an LLC or hire employees. Sole proprietors can use SSN.',
        category: 'registration',
        priority: 'medium',
        isRequired: false,
      },
      {
        id: 'us-tech-3',
        title: 'Open Business Bank Account',
        description: 'Separate your personal and business finances for easier accounting and tax filing.',
        category: 'registration',
        priority: 'high',
        isRequired: true,
      },
      {
        id: 'us-tech-4',
        title: 'Track Income and Expenses',
        description: 'Use accounting software (QuickBooks, Wave, FreshBooks) to track all income and deductible expenses.',
        category: 'ongoing',
        priority: 'high',
        isRequired: true,
      },
      {
        id: 'us-tech-5',
        title: 'Pay Quarterly Estimated Taxes',
        description: 'If you expect to owe $1,000+ in taxes, pay estimated taxes quarterly using IRS Form 1040-ES.',
        category: 'quarterly',
        priority: 'high',
        isRequired: true,
      },
      {
        id: 'us-tech-6',
        title: 'Issue 1099-NEC Forms',
        description: 'If you pay contractors $600+ per year, issue 1099-NEC by January 31.',
        category: 'annual',
        priority: 'medium',
        isRequired: false,
      },
      {
        id: 'us-tech-7',
        title: 'File Annual Tax Return',
        description: 'File Schedule C (Profit or Loss from Business) with your Form 1040 by April 15.',
        category: 'annual',
        priority: 'high',
        isRequired: true,
      },
      {
        id: 'us-tech-8',
        title: 'Pay Self-Employment Tax',
        description: 'Pay 15.3% self-employment tax (Social Security + Medicare) on net earnings using Schedule SE.',
        category: 'annual',
        priority: 'high',
        isRequired: true,
      },
      {
        id: 'us-tech-9',
        title: 'Consider Business Insurance',
        description: 'Get professional liability insurance (E&O) and general liability insurance.',
        category: 'registration',
        priority: 'medium',
        isRequired: false,
      },
      {
        id: 'us-tech-10',
        title: 'Keep Records for 7 Years',
        description: 'Maintain all tax records, receipts, invoices, and contracts for at least 7 years.',
        category: 'ongoing',
        priority: 'medium',
        isRequired: true,
      },
    ],
    taxDeadlines: [
      {
        name: 'Q1 Estimated Tax Payment',
        description: 'Pay estimated taxes for January-March income',
        frequency: 'quarterly',
        dueDate: 'April 15',
        penalty: 'Underpayment penalties may apply',
      },
      {
        name: 'Q2 Estimated Tax Payment',
        description: 'Pay estimated taxes for April-May income',
        frequency: 'quarterly',
        dueDate: 'June 15',
        penalty: 'Underpayment penalties may apply',
      },
      {
        name: 'Q3 Estimated Tax Payment',
        description: 'Pay estimated taxes for June-August income',
        frequency: 'quarterly',
        dueDate: 'September 15',
        penalty: 'Underpayment penalties may apply',
      },
      {
        name: 'Q4 Estimated Tax Payment',
        description: 'Pay estimated taxes for September-December income',
        frequency: 'quarterly',
        dueDate: 'January 15 (following year)',
        penalty: 'Underpayment penalties may apply',
      },
      {
        name: 'Annual Tax Return',
        description: 'File Form 1040 with Schedule C and Schedule SE',
        frequency: 'annual',
        dueDate: 'April 15',
        penalty: 'Late filing penalties: 5% per month up to 25%',
      },
      {
        name: 'Issue 1099-NEC to Contractors',
        description: 'If you paid contractors $600+, issue 1099-NEC forms',
        frequency: 'annual',
        dueDate: 'January 31',
        penalty: 'Penalties range from $50-$290 per form',
      },
    ],
    resources: [
      {
        title: 'IRS Self-Employment Tax Guide',
        url: 'https://www.irs.gov/businesses/small-businesses-self-employed/self-employment-tax-social-security-and-medicare-taxes',
        type: 'official',
      },
      {
        title: 'IRS Estimated Tax Calculator',
        url: 'https://www.irs.gov/individuals/tax-withholding-estimator',
        type: 'calculator',
      },
      {
        title: 'Freelancers Union Tax Guide',
        url: 'https://www.freelancersunion.org/resources/tax-guide/',
        type: 'guide',
      },
    ],
  },

  // India - Tech Freelancer Compliance
  {
    country: 'India',
    industry: 'tech',
    name: 'India Tech Freelancer Compliance Checklist',
    description: 'Basic tax and GST compliance checklist for Indian technology freelancers',
    version: 1,
    isActive: true,
    items: [
      {
        id: 'india-tech-1',
        title: 'Obtain PAN Card',
        description: 'Permanent Account Number is mandatory for all taxpayers in India. Apply at NSDL or UTIITSL.',
        category: 'registration',
        priority: 'high',
        isRequired: true,
      },
      {
        id: 'india-tech-2',
        title: 'Register for GST (if turnover > ₹20 lakhs)',
        description: 'If your annual turnover exceeds ₹20 lakhs (₹10 lakhs for special category states), GST registration is mandatory.',
        category: 'registration',
        priority: 'high',
        isRequired: false,
      },
      {
        id: 'india-tech-3',
        title: 'Open Business Bank Account',
        description: 'Separate business and personal finances. Required for GST and professional transactions.',
        category: 'registration',
        priority: 'high',
        isRequired: true,
      },
      {
        id: 'india-tech-4',
        title: 'Maintain Books of Accounts',
        description: 'If income > ₹2.5 lakhs or turnover > ₹25 lakhs, maintain proper books of accounts.',
        category: 'ongoing',
        priority: 'high',
        isRequired: true,
      },
      {
        id: 'india-tech-5',
        title: 'Pay Advance Tax Quarterly',
        description: 'If tax liability > ₹10,000, pay advance tax in 4 installments (June, Sept, Dec, March).',
        category: 'quarterly',
        priority: 'high',
        isRequired: true,
      },
      {
        id: 'india-tech-6',
        title: 'File GSTR-1 (GST Return)',
        description: 'If registered for GST, file GSTR-1 (outward supplies) by 11th of following month.',
        category: 'monthly',
        priority: 'high',
        isRequired: false,
      },
      {
        id: 'india-tech-7',
        title: 'File GSTR-3B (GST Return)',
        description: 'If registered for GST, file GSTR-3B (summary return) by 20th of following month.',
        category: 'monthly',
        priority: 'high',
        isRequired: false,
      },
      {
        id: 'india-tech-8',
        title: 'File Annual ITR (Income Tax Return)',
        description: 'File ITR-3 or ITR-4 (depending on your business structure) by July 31.',
        category: 'annual',
        priority: 'high',
        isRequired: true,
      },
      {
        id: 'india-tech-9',
        title: 'File Annual GST Return (GSTR-9)',
        description: 'If GST registered, file annual return GSTR-9 by December 31.',
        category: 'annual',
        priority: 'medium',
        isRequired: false,
      },
      {
        id: 'india-tech-10',
        title: 'Deduct TDS on Professional Fees',
        description: 'If you receive payments from companies, ensure TDS is deducted and you receive Form 16A.',
        category: 'ongoing',
        priority: 'medium',
        isRequired: true,
      },
      {
        id: 'india-tech-11',
        title: 'Issue Tax Invoices',
        description: 'Issue proper tax invoices (with GST details if registered) for all services provided.',
        category: 'ongoing',
        priority: 'high',
        isRequired: true,
      },
      {
        id: 'india-tech-12',
        title: 'Consider Professional Tax',
        description: 'Some states require professional tax registration. Check your state requirements.',
        category: 'registration',
        priority: 'low',
        isRequired: false,
      },
    ],
    taxDeadlines: [
      {
        name: 'GSTR-1 Filing',
        description: 'File details of outward supplies (sales)',
        frequency: 'monthly',
        dueDate: '11th of following month',
        penalty: 'Late fee: ₹200 per day (₹100 CGST + ₹100 SGST), max ₹5,000',
      },
      {
        name: 'GSTR-3B Filing',
        description: 'File summary GST return and pay tax',
        frequency: 'monthly',
        dueDate: '20th of following month',
        penalty: 'Late fee: ₹50 per day (₹25 CGST + ₹25 SGST), max ₹5,000',
      },
      {
        name: 'Advance Tax - 1st Installment',
        description: 'Pay 15% of estimated annual tax',
        frequency: 'quarterly',
        dueDate: 'June 15',
        penalty: 'Interest at 1% per month on shortfall',
      },
      {
        name: 'Advance Tax - 2nd Installment',
        description: 'Pay 45% of estimated annual tax (cumulative)',
        frequency: 'quarterly',
        dueDate: 'September 15',
        penalty: 'Interest at 1% per month on shortfall',
      },
      {
        name: 'Advance Tax - 3rd Installment',
        description: 'Pay 75% of estimated annual tax (cumulative)',
        frequency: 'quarterly',
        dueDate: 'December 15',
        penalty: 'Interest at 1% per month on shortfall',
      },
      {
        name: 'Advance Tax - 4th Installment',
        description: 'Pay 100% of estimated annual tax',
        frequency: 'quarterly',
        dueDate: 'March 15',
        penalty: 'Interest at 1% per month on shortfall',
      },
      {
        name: 'Income Tax Return (ITR)',
        description: 'File ITR-3 or ITR-4 for the previous financial year',
        frequency: 'annual',
        dueDate: 'July 31',
        penalty: 'Late fee: ₹5,000 (₹1,000 if income < ₹5 lakhs)',
      },
      {
        name: 'Annual GST Return (GSTR-9)',
        description: 'File annual GST return for previous financial year',
        frequency: 'annual',
        dueDate: 'December 31',
        penalty: 'Late fee: ₹200 per day (₹100 CGST + ₹100 SGST)',
      },
    ],
    resources: [
      {
        title: 'Income Tax Department - Official Portal',
        url: 'https://www.incometax.gov.in/',
        type: 'official',
      },
      {
        title: 'GST Portal - Official',
        url: 'https://www.gst.gov.in/',
        type: 'official',
      },
      {
        title: 'Income Tax Calculator',
        url: 'https://www.incometax.gov.in/iec/foportal/',
        type: 'calculator',
      },
      {
        title: 'Cleartax - Freelancer Tax Guide',
        url: 'https://cleartax.in/s/freelance-income-tax',
        type: 'guide',
      },
    ],
  },
];
